name: C/C++ CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
    - name: Run tests
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          ./build/MainTest --gtest_output=xml:output.xml
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ./build/MainTest --gtest_output=xml:output.xml
        elif [ "$RUNNER_OS" == "Windows" ]; then
          ./build/Release/MainTest.exe --gtest_output=xml:output.xml
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
